name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'Dockerfile'
      - '.github/workflows/continuous-delivery.yml'
  workflow_dispatch:

jobs:
  PublishDragooning:
    name: Publish dragoon.ing image to container registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push dragooning Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: ./
          file: Dockerfile
          tags: ghcr.io/favware/dragoon.ing:latest
